### ISSUE TITLE
Performance

### ISSUE THREAD

**Issue by andreasdc** [vectrix-space/flare#40]
Was there any tests done? From what I see SyncMap has worse performance than ConcurrentHashMap, are there any benchmarks? When using flare will be better than normal hashmap/fastutil?

**Comment by connorhartley** [comment]
`SyncMap` is a specialized map, you should read the javadocs to understand how it is useful (https://github.com/vectrix-space/flare/blob/main/flare/src/main/java/space/vectrix/flare/SyncMap.java#L39).

There are benchmarks recorded here (https://github.com/vectrix-space/flare/blob/main/benchmark/readme.md).

**Comment by connorhartley** [comment]
Also if you have questions to ask, I'd prefer that you ask them in the Discord over creating issues for them.
